base_url = "https://vinidlidoo.github.io"
title = "vinidlidoo"
description = "A personal blog"
default_language = "en"
theme = "tabi"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]

build_search_index = false

taxonomies = [{ name = "tags" }]

[languages.fr]
title = "vinidlidoo"
description = "Un blog personnel"
taxonomies = [{ name = "tags" }]

[languages.ja]
title = "vinidlidoo"
description = "ÂÄã‰∫∫„Éñ„É≠„Ç∞"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Vincent"
stylesheets = ["css/details.css", "css/giscus-fix.css"]
skin = "indigo_ingot"
compact_tags = true
tag_sorting = "frequency"
favicon = "img/favicon.png"
menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "tags", url = "tags", trailing_slash = true },
]
socials = [
  { name = "github", url = "https://github.com/vinidlidoo", icon = "github" },
  { name = "x", url = "https://x.com/vinidlidoo", icon = "x" },
]
copyright = "¬© $CURRENT_YEAR Vincent Ethier"
allowed_domains = [
  { directive = "font-src", domains = [
    "'self'",
    "data:",
  ] },
  { directive = "script-src", domains = [
    "platform.twitter.com",
    "giscus.app",
  ] },
  { directive = "frame-src", domains = [
    "platform.twitter.com",
    "giscus.app",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "data:",
  ] },
]

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "vinidlidoo/vinidlidoo.github.io"
repo_id = "R_kgDOQ0WZSA"
category = "üë®‚Äçüíª Blog"
category_id = "DIC_kwDOQ0WZSM4C1LA8"
mapping = "slug"
strict_title_matching = 0
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""
lazy_loading = true
