base_url = "https://vinidlidoo.github.io"
title = "vinidlidoo"
description = "A personal blog"
default_language = "en"
theme = "tabi"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]

build_search_index = true

taxonomies = [{ name = "tags" }]

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true

[link_checker]
skip_prefixes = ["https://journals.sagepub.com/"]

[languages.fr]
title = "vinidlidoo"
description = "Un blog personnel"
build_search_index = true
taxonomies = [{ name = "tags" }]

[languages.fr.search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true

[languages.ja]
title = "vinidlidoo"
description = "ÂÄã‰∫∫„Éñ„É≠„Ç∞"
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
style = "class"
theme = "catppuccin-frappe"

[extra]
newsletter_action = "https://buttondown.com/api/emails/embed-subscribe/vinidlidoo"
contact_form_action = "https://formspree.io/f/xeekqdav"
author = "Vincent"
stylesheets = ["css/details.css", "css/giscus-fix.css", "css/newsletter.css", "css/contact.css"]
skin = "indigo_ingot"
compact_tags = true
tag_sorting = "frequency"
favicon = "img/favicon.png"
menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "tags", url = "tags", trailing_slash = true },
  { name = "contact", url = "contact", trailing_slash = true },
]
socials = [
  { name = "github", url = "https://github.com/vinidlidoo", icon = "github" },
  { name = "x", url = "https://x.com/vinidlidoo", icon = "x" },
]
copyright = "¬© $CURRENT_YEAR Vincent Ethier"
allowed_domains = [
  { directive = "font-src", domains = [
    "'self'",
    "data:",
  ] },
  { directive = "script-src", domains = [
    "platform.twitter.com",
    "giscus.app",
  ] },
  { directive = "frame-src", domains = [
    "platform.twitter.com",
    "giscus.app",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "data:",
    "pub-94e31bf482a74272bb61e9559b598705.r2.dev",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "pub-94e31bf482a74272bb61e9559b598705.r2.dev",
  ] },
  { directive = "form-action", domains = [
    "'self'",
    "buttondown.com",
    "formspree.io",
  ] },
]

[extra.giscus]
enabled_for_all_posts = false
automatic_loading = true
repo = "vinidlidoo/vinidlidoo.github.io"
repo_id = "R_kgDOQ0WZSA"
category = "üë®‚Äçüíª Blog"
category_id = "DIC_kwDOQ0WZSM4C1LA8"
mapping = "slug"
strict_title_matching = 0
enable_reactions = 1
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""
lazy_loading = true
