base_url = "https://vinidlidoo.github.io"
title = "vinidlidoo"
description = "A personal blog"
default_language = "en"
theme = "tabi"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]

build_search_index = false

taxonomies = [{ name = "tags" }]

[languages.fr]
title = "vinidlidoo"
description = "Un blog personnel"
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Vincent"
stylesheets = ["css/details.css"]
skin = "indigo_ingot"
compact_tags = true
tag_sorting = "frequency"
favicon = "img/favicon.png"
menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "tags", url = "tags", trailing_slash = true },
]
socials = [
  { name = "github", url = "https://github.com/vinidlidoo", icon = "github" },
  { name = "x", url = "https://x.com/vinidlidoo", icon = "x" },
]
copyright = "Â© $CURRENT_YEAR Vincent Ethier"
allowed_domains = [
  { directive = "script-src", domains = [
    "platform.twitter.com",
  ] },
  { directive = "frame-src", domains = [
    "platform.twitter.com",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "data:",
  ] },
]
